features(server/ handler-model minimal fixes)
NahuelMedina/idiomasMasterBack pull request #26
Opened 2024-02-17 18:10 UTC by tomaspon

handler getUser / model User - minimal fixes

2024-02-17 18:18 UTC, bauticalvo approved these changes

2024-02-18 14:10 UTC, GasparMon requested changes
Se estan pisando correcciones que se hicieron en los modelos para que funcione, traete los nuevos cambios antes de hacer el pull

2024-02-18 18:28 UTC, SAndresArboleda approved these changes
ok

2024-02-18 18:28 UTC, GasparMon approved these changes

2024-02-18 18:28 UTC, merged